In [36]:
import numpy as np
import pandas as pd
import copy

df = pd.DataFrame({
    'Athlete':['Michael Phelp','Michael Phelp','Michael Phelp','Natalie Coughlin','Aleksey Nemov'],
    'Age':[23,19,27,25,24],
    'Country' :['United States','Canada','United States','Norway','China'],
    'Year':[2008,2004,2012,2008,2000],
    'Gold Medals':[8,6,4,1,4]
}, columns=['Athlete','Age','Country','Year','Gold Medals'])
df

            Athlete  Age        Country  Year  Gold Medals
0     Michael Phelp   23  United States  2008            8
1     Michael Phelp   19         Canada  2004            6
2     Michael Phelp   27  United States  2012            4
3  Natalie Coughlin   25         Norway  2008            1
4     Aleksey Nemov   24          China  2000            4

In [37]:
#Tugas No. 1
df.loc[df['Country'] == 'United States']

         Athlete  Age        Country  Year  Gold Medals
0  Michael Phelp   23  United States  2008            8
2  Michael Phelp   27  United States  2012            4

In [38]:
#Tugas No. 2

df2 = df[["Athlete","Year"]]
df2.loc[df['Year'] == 2008]

            Athlete  Year
0     Michael Phelp  2008
3  Natalie Coughlin  2008

In [39]:
#Tugas No. 3

condition_a = df['Age'] > 2
condition_b = df['Country'] == 'Norway'
combined_condition = condition_a & condition_b
df3 = df[~combined_condition]
df4 = copy.deepcopy(df3)
df4

         Athlete  Age        Country  Year  Gold Medals
0  Michael Phelp   23  United States  2008            8
1  Michael Phelp   19         Canada  2004            6
2  Michael Phelp   27  United States  2012            4
4  Aleksey Nemov   24          China  2000            4

In [45]:
#Tugas No. 4
df['Silver Medal'] = pd.Series([0,0,2,np.nan,1])
df['Bronze Medal'] = pd.Series([0,2,0,np.nan,3])

condition_a = df['Age'] > 2
condition_b = df['Country'] == 'Norway'
combined_condition = condition_a & condition_b
df5 = df[~combined_condition]
df6 = copy.deepcopy(df3)
df6

,Athlete,Age,Country,Year,Gold Medals,Silver Medal,Bronze Medal
0,Michael Phelp,23,United States,2008,8,0.0,0.0
1,Michael Phelp,19,Canada,2004,6,0.0,2.0
2,Michael Phelp,27,United States,2012,4,2.0,0.0
3,Natalie Coughlin,25,Norway,2008,1,NaN,NaN
4,Aleksey Nemov,24,China,2000,4,1.0,3.0